import {
  StudentProfile,
  Workshop,
  Speaker,
  AttendanceRecord,
  ComplementaryActivity,
  MomentPost,
  CourseModule,
  Badge,
} from './types';

export const INITIAL_STUDENT: StudentProfile = {
  id: 'aluno-01',
  name: 'Mariana Vasconcelos',
  email: 'mariana.vasconcelos@aluno.ce.gov.br',
  cpf: '482.915.630-72',
  matricula: 'AE-2026-0491',
  courseName: 'Programa Aluno Empreendedor - Jovens Criadores de Startups',
  turma: 'Turma 2026.1',
  institution: 'Secretaria da Educação & Hub de Inovação',
  avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400&auto=format&fit=crop&q=80',
  facialEnrolled: true,
  facialConfidence: 98.6,
  lastLogin: 'Hoje, às 08:30',
};

export const INITIAL_SPEAKERS: Speaker[] = [
  {
    id: 'spk-daniele',
    name: 'Profª. Daniele Rodrigues de Lima',
    role: 'Professora de Química',
    company: 'Programa Aluno Empreendedor & SASP',
    bio: 'Professora de Química no Programa Aluno Empreendedor. Especialista em transformações químicas dos alimentos, reações culinárias, técnicas de fermentação, conservação e desenvolvimento prático de receitas inovadoras.',
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=400&auto=format&fit=crop&q=80',
    expertise: ['Química', 'Química dos Alimentos', 'Pães Recheados', 'Processos Produtivos'],
    workshopIds: ['ws-1', 'ws-3'],
    linkedinUrl: '',
    email: 'daniele.rodrigues@prof.ce.gov.br',
  },
  {
    id: 'spk-elvis',
    name: 'Dr. Elvis Franklin Fernandes de Carvalho',
    role: 'Prof. Ciências / Biologia',
    company: 'Programa Aluno Empreendedor & SASP',
    bio: 'Doutor e Professor de Ciências e Biologia no Programa Aluno Empreendedor. Especialista em microbiologia aplicada aos alimentos, vigilância e boas práticas sanitárias, biossegurança e controle de qualidade nos negócios.',
    avatar: 'https://images.unsplash.com/photo-1560250097-0b93528c311a?w=400&auto=format&fit=crop&q=80',
    expertise: ['Ciências / Biologia', 'Boas Práticas', 'Microbiologia Alimentar', 'Segurança Sanitária'],
    workshopIds: ['ws-4'],
    linkedinUrl: '',
    email: 'elvis.carvalho@prof.ce.gov.br',
  },
  {
    id: 'spk-izac',
    name: 'Prof. Izac Dalva Montenegro Fernanda Filho',
    role: 'Professor de Matemática',
    company: 'Programa Aluno Empreendedor & SASP',
    bio: 'Professor de Matemática no Programa Aluno Empreendedor. Especialista em matemática financeira voltada a pequenos negócios: cálculo de custos, margens de contribuição, formação do preço de venda e equilíbrio financeiro.',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&auto=format&fit=crop&q=80',
    expertise: ['Matemática', 'Matemática Financeira', 'Cálculo de Margens', 'Custos & Preços'],
    workshopIds: ['ws-2', 'ws-5'],
    linkedinUrl: '',
    email: 'izac.fernandes@prof.ce.gov.br',
  },
  {
    id: 'spk-1',
    name: 'Drª. Juliana Queiroz & Dr. Lucas Silveira',
    role: 'Mentores de Negócios & Inovação',
    company: 'Hub de Inovação & Secretaria da Educação',
    bio: 'Especialistas em ideação, validação ágil e criação de fontes de renda a partir do zero para estudantes e jovens empreendedores.',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400&auto=format&fit=crop&q=80',
    expertise: ['Do Zero ao Primeiro Negócio', 'Transformando Ideias em Renda', 'Ideação'],
    workshopIds: ['ws-1'],
    linkedinUrl: '',
    email: 'juliana.queiroz1@prof.ce.gov.br',
  },
  {
    id: 'spk-5',
    name: 'Paulo Morais & Beatriz Menezes',
    role: 'Consultores Especialistas Sebrae',
    company: 'Sebrae Nacional / Regional CE',
    bio: 'Consultores especialistas do Sebrae em precificação para alimentação fora do lar, estratégias de vendas digitais e atendimento encantador ao cliente.',
    avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=400&auto=format&fit=crop&q=80',
    expertise: ['Sebrae EAD', 'Preço de Vendas', 'Atendimento ao Cliente'],
    workshopIds: ['ws-5', 'ws-6'],
    linkedinUrl: '',
    email: 'paulo.morais@sebraece.com.br',
  },
];

export const INITIAL_WORKSHOPS: Workshop[] = [
  {
    id: 'ws-1',
    title: 'Mentoria do Zero ao Primeiro Negócio: Transformando Ideias em Renda',
    category: 'Mentoria & Ideação',
    date: '10/09/2026',
    time: '18h - 21h',
    durationHours: 3,
    speakerId: 'spk-daniele',
    speakerName: 'Profª. Daniele Rodrigues de Lima',
    speakerRole: 'Professora de Química',
    location: 'SASP',
    description: 'Como transformar ideias em fontes de renda real: mapeamento de oportunidades na comunidade, validação rápida e estruturação dos primeiros passos sem necessidade de grande capital inicial.',
    tags: ['Do Zero ao Negócio', 'Transformando Ideias em Renda', 'Ideação'],
    status: 'hoje',
    evaluation: {
      rating: 5,
      speakerRating: 5,
      contentApplicability: 5,
      feedback: 'Mentoria sensacional! Abriu a mente sobre como faturar rápido com produtos que já sabemos fazer.',
      submittedAt: '10/09/2026 21:15',
    },
    materials: [],
  },
  {
    id: 'ws-2',
    title: 'Matemática Financeira',
    category: 'Finanças & Gestão',
    date: '24/09/2026',
    time: '18h - 21h',
    durationHours: 3,
    speakerId: 'spk-izac',
    speakerName: 'Prof. Izac Dalva Montenegro Fernanda Filho',
    speakerRole: 'Professor de Matemática',
    location: 'SASP',
    description: 'Matemática financeira essencial para quem vende: cálculo de margens de contribuição, despesas fixas e variáveis, ponto de equilíbrio e planejamento de fluxo de caixa para não faltar dinheiro.',
    tags: ['Matemática Financeira', 'Custos', 'Margem de Lucro'],
    status: 'proxima',
    materials: [],
  },
  {
    id: 'ws-3',
    title: 'Pães Recheados',
    category: 'Gastronomia & Produção',
    date: '01/10/2026',
    time: '18h - 21h',
    durationHours: 3,
    speakerId: 'spk-daniele',
    speakerName: 'Profª. Daniele Rodrigues de Lima',
    speakerRole: 'Professora de Química',
    location: 'SASP',
    description: 'Oficina prática "mão na massa": química da fermentação e massas, produção de pães artesanais recheados (doces e salgados), ponto da massa, padronização de porções e rendimento comercial.',
    tags: ['Pães Recheados', 'Panificação', 'Química dos Alimentos', 'Gastronomia Prática'],
    status: 'proxima',
    materials: [],
  },
  {
    id: 'ws-4',
    title: 'Boas Práticas',
    category: 'Higiene & Normas Sanitárias',
    date: '22/10/2026',
    time: '18h - 21h',
    durationHours: 3,
    speakerId: 'spk-elvis',
    speakerName: 'Dr. Elvis Franklin Fernandes de Carvalho',
    speakerRole: 'Prof. Ciências / Biologia',
    location: 'SASP',
    description: 'Manual de boas práticas na manipulação de alimentos: biossegurança, microbiologia dos alimentos, higienização de bancadas, controle térmico, rotulagem e conformidade sanitária.',
    tags: ['Boas Práticas', 'Ciências / Biologia', 'Vigilância Sanitária', 'Segurança Alimentar'],
    status: 'proxima',
    materials: [],
  },
  {
    id: 'ws-5',
    title: 'Curso EAD Sebrae: Preço de Vendas para Alimentação Fora do Lar',
    category: 'Sebrae EAD & Precificação',
    date: '04/11/2026',
    time: '18h - 21h',
    durationHours: 3,
    speakerId: 'spk-izac',
    speakerName: 'Paulo Morais & Prof. Izac Dalva Montenegro',
    speakerRole: 'Consultor Sebrae & Prof. de Matemática',
    location: 'Sebrae EAD (Online)',
    description: 'Formação certificada Sebrae EAD sobre formação de preços na alimentação: custo das matérias-primas (CMV), perdas na produção, markup multiplicador e estratégias de combos promocionais.',
    tags: ['Sebrae EAD', 'Preço de Vendas', 'Alimentação Fora do Lar', 'Matemática'],
    status: 'proxima',
    materials: [],
  },
  {
    id: 'ws-6',
    title: 'Curso EAD Sebrae: Atendimento ao Cliente',
    category: 'Sebrae EAD & Vendas',
    date: '11/11/2026',
    time: '18h - 21h',
    durationHours: 3,
    speakerId: 'spk-5',
    speakerName: 'Beatriz Menezes',
    speakerRole: 'Consultora de Vendas & Atendimento Sebrae',
    location: 'Sebrae EAD (Online)',
    description: 'Como encantar e fidelizar clientes: postura profissional, comunicação empática, atendimento ágil pelo WhatsApp, resolução de reclamações e estratégias de recompra.',
    tags: ['Sebrae EAD', 'Atendimento ao Cliente', 'Fidelização', 'Vendas'],
    status: 'proxima',
    materials: [],
  },
  {
    id: 'ws-7',
    title: 'Dezembro: Encerramento e Feira Empreendedora',
    category: 'Feira & Conclusão',
    date: '02/12/2026',
    time: '18h - 21h',
    durationHours: 3,
    speakerId: 'spk-1',
    speakerName: 'Drª. Juliana Queiroz & Professores',
    speakerRole: 'Coordenação e Banca Avaliadora',
    location: 'SASP (Feira Empreendedora)',
    description: 'Grande Feira Empreendedora de Encerramento: montagem dos estandes pelos alunos, comercialização aberta dos produtos gastronômicos, pitch de encerramento e entrega de certificados.',
    tags: ['Feira Empreendedora', 'Encerramento', 'Vendas Reais', 'Formatura'],
    status: 'proxima',
    materials: [],
  },
];

export const INITIAL_ATTENDANCE: AttendanceRecord[] = [
  {
    id: 'att-1',
    workshopId: 'ws-1',
    workshopTitle: 'Mentoria do Zero ao Primeiro Negócio: Transformando Ideias em Renda',
    date: 'Hoje (10/09/2026)',
    time: '18h - 21h',
    hours: 3,
    status: 'presente',
    checkInMethod: 'biometria_facial',
    checkInTime: '17:54:12',
    location: 'Auditório Principal - Totem Biometria',
  },
  {
    id: 'att-2',
    workshopId: 'ws-2',
    workshopTitle: 'Matemática Financeira',
    date: '24/09/2026',
    time: '18h - 21h',
    hours: 3,
    status: 'presente',
    checkInMethod: 'biometria_facial',
    checkInTime: '17:58:30',
    location: 'Laboratório de Informática 01',
  },
  {
    id: 'att-3',
    workshopId: 'ws-3',
    workshopTitle: 'Pães Recheados',
    date: '01/10/2026',
    time: '18h - 21h',
    hours: 3,
    status: 'presente',
    checkInMethod: 'biometria_facial',
    checkInTime: '17:52:05',
    location: 'Cozinha Didática / Laboratório Gastronômico',
  },
  {
    id: 'att-4',
    workshopId: 'ws-4',
    workshopTitle: 'Boas Práticas',
    date: '22/10/2026',
    time: '18h - 21h',
    hours: 3,
    status: 'presente',
    checkInMethod: 'biometria_facial',
    checkInTime: '18:01:20',
    location: 'Laboratório Gastronômico',
  },
  {
    id: 'att-5',
    workshopId: 'ws-5',
    workshopTitle: 'Curso EAD Sebrae: Preço de Vendas para Alimentação Fora do Lar',
    date: '04/11/2026',
    time: '18h - 21h',
    hours: 3,
    status: 'presente',
    checkInMethod: 'online_ead',
    checkInTime: '18:00:00',
    location: 'Ambiente Virtual Sebrae / Sala Conectada',
  },
  {
    id: 'att-6',
    workshopId: 'ws-6',
    workshopTitle: 'Curso EAD Sebrae: Atendimento ao Cliente',
    date: '11/11/2026',
    time: '18h - 21h',
    hours: 3,
    status: 'presente',
    checkInMethod: 'online_ead',
    checkInTime: '18:00:00',
    location: 'Ambiente Virtual Sebrae / Sala Conectada',
  },
  {
    id: 'att-7',
    workshopId: 'ws-7',
    workshopTitle: 'Dezembro: Encerramento e Feira Empreendedora',
    date: '02/12/2026',
    time: '18h - 21h',
    hours: 3,
    status: 'presente',
    checkInMethod: 'biometria_facial',
    checkInTime: '17:49:15',
    location: 'Pátio Central - Estandes de Exposição',
  },
];

export const INITIAL_COMPLEMENTARY_ACTIVITIES: ComplementaryActivity[] = [
  {
    id: 'act-1',
    title: 'Curso Online Sebrae: Empreendedorismo como Opção de Carreira',
    category: 'Curso Online',
    workloadHours: 15,
    date: '12/03/2026',
    description: 'Curso com 6 módulos abordando perfil empreendedor, busca por oportunidades, rede de contatos e persistência.',
    proofFileName: 'Certificado_Sebrae_Empreendedorismo_Mariana.pdf',
    status: 'aprovado',
    feedback: 'Atividade homologada com sucesso! Carga horária contabilizada.',
  },
  {
    id: 'act-2',
    title: 'Visita Técnica ao Hub de Inovação Ninna & Startups Residentes',
    category: 'Visita Técnica',
    workloadHours: 8,
    date: '18/03/2026',
    description: 'Visita guiada conhecendo a rotina de 3 startups de tecnologia e participando de uma sessão de ideação coletiva.',
    proofFileName: 'Comprovante_Visita_Ninna_Hub.pdf',
    status: 'aprovado',
    feedback: 'Excelente relatório de visita técnica anexado.',
  },
  {
    id: 'act-3',
    title: 'Leitura e Resenha Crítica: "A Startup Enxuta" de Eric Ries',
    category: 'Leitura de Livro',
    workloadHours: 10,
    date: '20/03/2026',
    description: 'Resumo analítico destacando o ciclo Construir-Medir-Aprender aplicado ao nosso projeto de marketplace sustentável.',
    proofFileName: 'Resenha_Startup_Enxuta_Mariana.docx',
    status: 'aprovado',
    feedback: 'Muito boa conexão entre a teoria do livro e o protótipo da equipe.',
  },
];

export const INITIAL_MOMENTS: MomentPost[] = [
  {
    id: 'mom-1',
    title: 'Nosso Canvas completo na parede!',
    caption: 'Depois de 3 horas debatendo a proposta de valor e entrevistando 15 colegas no intervalo, fechamos a primeira versão do nosso Modelo de Negócio! 🚀💡',
    imageUrl: 'https://images.unsplash.com/photo-1531403009284-440f080d1e12?w=800&auto=format&fit=crop&q=80',
    date: '02 de Março, 2026',
    authorName: 'Mariana Vasconcelos',
    authorAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400&auto=format&fit=crop&q=80',
    tags: ['#Canvas', '#EquipeInovadora', '#AlunoEmpreendedor'],
    likes: 24,
    isLiked: true,
  },
  {
    id: 'mom-2',
    title: 'Calculando a precificação do nosso protótipo',
    caption: 'Com a ajuda da mentora Camila Albuquerque, descobrimos onde estávamos perdendo margem e recalculamos nosso preço unitário. Foco na sustentabilidade financeira!',
    imageUrl: 'https://images.unsplash.com/photo-1554224155-8d04cb21cd6c?w=800&auto=format&fit=crop&q=80',
    date: '09 de Março, 2026',
    authorName: 'Mariana Vasconcelos',
    authorAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400&auto=format&fit=crop&q=80',
    tags: ['#Finanças', '#Precificação', '#Gestão'],
    likes: 19,
    isLiked: false,
  },
  {
    id: 'mom-3',
    title: 'Ensaio geral do Pitch de 3 minutos',
    caption: 'Treinando postura, respiração e cronometrando os 180 segundos. Dá um frio na barriga mas ver a ideia tomando forma não tem preço!',
    imageUrl: 'https://images.unsplash.com/photo-1475721027785-f74eccf877e2?w=800&auto=format&fit=crop&q=80',
    date: '21 de Março, 2026',
    authorName: 'Mariana Vasconcelos',
    authorAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400&auto=format&fit=crop&q=80',
    tags: ['#PitchDay', '#Oratória', '#Confiança'],
    likes: 38,
    isLiked: true,
  },
];

export const INITIAL_MODULES: CourseModule[] = [
  {
    id: 'mod-1',
    code: 'OFI-01',
    title: 'Mentoria do Zero ao Primeiro Negócio: Transformando Ideias em Renda',
    description: 'Mapeamento de oportunidades na comunidade, validação rápida e primeiros passos de faturamento.',
    totalHours: 3,
    completedHours: 3,
    status: 'concluido',
    competencies: ['Ideação', 'Do Zero ao Primeiro Negócio', 'Transformando Ideias em Renda'],
  },
  {
    id: 'mod-2',
    code: 'OFI-02',
    title: 'Matemática Financeira: Custos, Margem e Ponto de Equilíbrio',
    description: 'Cálculo de margens de contribuição, despesas fixas e variáveis e fluxo de caixa com Prof. Izac.',
    totalHours: 3,
    completedHours: 3,
    status: 'concluido',
    competencies: ['Matemática Financeira', 'Margem de Lucro', 'Custos & Preços'],
  },
  {
    id: 'mod-3',
    code: 'OFI-03',
    title: 'Panificação Artesanal: Pães Recheados & Química dos Alimentos',
    description: 'Química da fermentação, ponto da massa, receitas doces e salgadas e rendimento com Profª Daniele.',
    totalHours: 3,
    completedHours: 3,
    status: 'concluido',
    competencies: ['Pães Recheados', 'Química dos Alimentos', 'Processos Produtivos'],
  },
  {
    id: 'mod-4',
    code: 'OFI-04',
    title: 'Boas Práticas Sanitárias & Microbiologia na Manipulação de Alimentos',
    description: 'Biossegurança, vigilância sanitária, higiene de bancadas e rotulagem com Dr. Elvis.',
    totalHours: 3,
    completedHours: 3,
    status: 'concluido',
    competencies: ['Boas Práticas', 'Ciências / Biologia', 'Segurança Sanitária'],
  },
  {
    id: 'mod-5',
    code: 'OFI-05',
    title: 'Curso EAD Sebrae: Preço de Vendas para Alimentação Fora do Lar',
    description: 'Formação online certificada Sebrae: CMV, perdas na produção, markup multiplicador e combos.',
    totalHours: 3,
    completedHours: 3,
    status: 'concluido',
    competencies: ['Sebrae EAD', 'Preço de Vendas', 'Alimentação Fora do Lar'],
  },
  {
    id: 'mod-6',
    code: 'OFI-06',
    title: 'Curso EAD Sebrae: Atendimento Encantador ao Cliente',
    description: 'Comunicação empática, atendimento ágil por WhatsApp, pós-venda e fidelização.',
    totalHours: 3,
    completedHours: 3,
    status: 'concluido',
    competencies: ['Sebrae EAD', 'Atendimento ao Cliente', 'Fidelização de Clientes'],
  },
  {
    id: 'mod-7',
    code: 'OFI-07',
    title: 'Encerramento: Grande Feira Empreendedora & Entrega de Certificados',
    description: 'Montagem de estandes, venda aberta ao público, pitch final e formatura no polo SASP.',
    totalHours: 3,
    completedHours: 3,
    status: 'concluido',
    competencies: ['Feira Empreendedora', 'Vendas Reais', 'Pitch & Formatura'],
  },
];

export const INITIAL_BADGES: Badge[] = [
  {
    id: 'bdg-1',
    title: 'Rosto Autenticado',
    category: 'Biometria',
    icon: 'ScanFace',
    description: 'Completou o login com reconhecimento facial e biometria ativa.',
    unlocked: true,
    unlockedDate: '01/03/2026',
  },
  {
    id: 'bdg-2',
    title: 'Presença Ouro (100%)',
    category: 'Frequência',
    icon: 'CheckCircle2',
    description: 'Participou pontualmente das oficinas do programa.',
    unlocked: true,
    unlockedDate: '16/03/2026',
  },
  {
    id: 'bdg-3',
    title: 'Mestre do Canvas',
    category: 'Modelagem',
    icon: 'Layers',
    description: 'Preencheu e validou todos os 9 blocos do Business Model Canvas.',
    unlocked: true,
    unlockedDate: '02/03/2026',
  },
  {
    id: 'bdg-4',
    title: 'Crítico Construtivo',
    category: 'Avaliação',
    icon: 'Star',
    description: 'Avaliou e forneceu feedback de qualidade sobre as oficinas.',
    unlocked: true,
    unlockedDate: '09/03/2026',
  },
  {
    id: 'bdg-5',
    title: 'Explorador de Horas',
    category: 'Atividades',
    icon: 'Award',
    description: 'Completou a meta de 30+ horas em atividades complementares.',
    unlocked: true,
    unlockedDate: '20/03/2026',
  },
  {
    id: 'bdg-6',
    title: 'Pitch Ready',
    category: 'Oratória',
    icon: 'Mic',
    description: 'Estruturou o roteiro e gravou o ensaio de pitch de 3 minutos.',
    unlocked: true,
    unlockedDate: '21/03/2026',
  },
];
